# Generated by Django 4.0 on 2022-10-17 00:02

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('news', 'Новость'), ('promo', 'Акция')], max_length=5, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications', verbose_name='Картинка')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Слаг')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('isVisible', models.BooleanField(blank=True, null=True, verbose_name='Видимая?')),
                ('inSlider', models.BooleanField(blank=True, null=True, verbose_name='Выводить в слайдер?')),
                ('availableUntill', models.DateTimeField(blank=True, null=True, verbose_name='Доступна до')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='PublicationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='publications/gallery', verbose_name='Картинка')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.publication', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Галерея публикации',
                'verbose_name_plural': 'Галереи публикаций',
            },
        ),
    ]
