# Generated by Django 4.0 on 2022-10-18 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='category',
        ),
    ]
