# Generated by Django 4.0 on 2022-10-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openTime', models.DateTimeField(verbose_name='Open Time')),
                ('open', models.FloatField(verbose_name='Open')),
                ('high', models.FloatField(verbose_name='High')),
                ('low', models.FloatField(verbose_name='Low')),
                ('close', models.FloatField(verbose_name='Close')),
                ('volume', models.FloatField(verbose_name='Volume')),
                ('closeTime', models.DateTimeField(verbose_name='Close Time')),
                ('quoteAssetVolume', models.FloatField(verbose_name='Quote Asset Volume')),
                ('numberOfTrades', models.IntegerField(verbose_name='Number Of Trades')),
                ('takerBuyBaseAssetVolume', models.FloatField(verbose_name='Taker buy base asset volume')),
                ('takerBuyQuoteAssetVolume', models.FloatField(verbose_name='Taker buy quote asset volume')),
            ],
            options={
                'verbose_name': 'Kline',
                'verbose_name_plural': 'Klines',
            },
        ),
    ]
