# Generated by Django 4.0 on 2022-11-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradesData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kline',
            old_name='close',
            new_name='Close',
        ),
        migrations.RenameField(
            model_name='kline',
            old_name='closeTime',
            new_name='CloseTime',
        ),
        migrations.RenameField(
            model_name='kline',
            old_name='openTime',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='kline',
            old_name='high',
            new_name='High',
        ),
        migrations.RenameField(
            model_name='kline',
            old_name='low',
            new_name='Low',
        ),
        migrations.RenameField(
            model_name='kline',
            old_name='numberOfTrades',
            new_name='NumberOfTrades',
        ),
        migrations.RenameField(
            model_name='kline',
            old_name='open',
            new_name='Open',
        ),
        migrations.RenameField(
            model_name='kline',
            old_name='quoteAssetVolume',
            new_name='QuoteAssetVolume',
        ),
        migrations.RenameField(
            model_name='kline',
            old_name='takerBuyBaseAssetVolume',
            new_name='TakerBuyBaseAssetVolume',
        ),
        migrations.RenameField(
            model_name='kline',
            old_name='takerBuyQuoteAssetVolume',
            new_name='TakerBuyQuoteAssetVolume',
        ),
        migrations.RenameField(
            model_name='kline',
            old_name='volume',
            new_name='Volume',
        ),
    ]
